#!/bin/bash

if [ "$#" -ne 1 ]
then
    echo "Usage: $0 <project>"
    exit 1
fi

project=$1

if [ ! -d $pico/$project ]
then
    echo "$0: $pico/$project directory does not exist"
    exit 1
fi
cd $pico/$project

if [ ! -d build ]
then 
    mkdir build
fi
cd build

cmake .. \
  -DCMAKE_C_COMPILER=/usr/bin/arm-none-eabi-gcc \
  -DCMAKE_CXX_COMPILER=/usr/bin/arm-none-eabi-g++ \
  -DCMAKE_ASM_COMPILER=/usr/bin/arm-none-eabi-gcc \
  -DPICO_SDK_PATH=~/projects/pico-sdk

make

if [ $? -eq 0 ]
then 
    cd $pico
    ctags -R .
fi
